name: Main
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: macos-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "zulu"

      - name: Build project
        run: ./gradlew buildDebug --stacktrace

      - name: Assemble Test APK
        run: ./gradlew hypertrace:assembleAndroidTest --stacktrace

      - name: Instrumented test
        uses: reactivecircus/android-emulator-runner@v2.23.0
        with:
          api-level: 16
          script: ./gradlew hypertrace:connectedAndroidTest --stacktrace
